name: Release on NPM

on:
  workflow_dispatch:
    inputs:
      type:
        description: A release type (path, minor or major)
        required: true
        default: patch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.type }}!"